import '../../l10n/app_localizations.dart';

/// Localized display name for a translate target language [code].
String translateLangDisplayName(AppLocalizations l10n, String code) {
  switch (code) {
    case 'en':
      return l10n.translateLangName_en;
    case 'ur':
      return l10n.translateLangName_ur;
    case 'hi':
      return l10n.translateLangName_hi;
    case 'ar':
      return l10n.translateLangName_ar;
    case 'es':
      return l10n.translateLangName_es;
    case 'fr':
      return l10n.translateLangName_fr;
    case 'de':
      return l10n.translateLangName_de;
    case 'pt':
      return l10n.translateLangName_pt;
    case 'ru':
      return l10n.translateLangName_ru;
    case 'zh':
      return l10n.translateLangName_zh;
    case 'zh-TW':
      return l10n.translateLangName_zhTw;
    case 'ja':
      return l10n.translateLangName_ja;
    case 'ko':
      return l10n.translateLangName_ko;
    case 'it':
      return l10n.translateLangName_it;
    case 'tr':
      return l10n.translateLangName_tr;
    case 'nl':
      return l10n.translateLangName_nl;
    case 'sv':
      return l10n.translateLangName_sv;
    case 'no':
      return l10n.translateLangName_no;
    case 'da':
      return l10n.translateLangName_da;
    case 'fi':
      return l10n.translateLangName_fi;
    case 'el':
      return l10n.translateLangName_el;
    case 'pl':
      return l10n.translateLangName_pl;
    case 'cs':
      return l10n.translateLangName_cs;
    case 'hu':
      return l10n.translateLangName_hu;
    case 'ro':
      return l10n.translateLangName_ro;
    case 'bg':
      return l10n.translateLangName_bg;
    case 'uk':
      return l10n.translateLangName_uk;
    case 'fa':
      return l10n.translateLangName_fa;
    case 'he':
      return l10n.translateLangName_he;
    case 'th':
      return l10n.translateLangName_th;
    case 'vi':
      return l10n.translateLangName_vi;
    case 'id':
      return l10n.translateLangName_id;
    case 'ms':
      return l10n.translateLangName_ms;
    case 'bn':
      return l10n.translateLangName_bn;
    case 'ta':
      return l10n.translateLangName_ta;
    case 'te':
      return l10n.translateLangName_te;
    case 'mr':
      return l10n.translateLangName_mr;
    case 'gu':
      return l10n.translateLangName_gu;
    case 'pa':
      return l10n.translateLangName_pa;
    case 'ml':
      return l10n.translateLangName_ml;
    case 'si':
      return l10n.translateLangName_si;
    case 'ne':
      return l10n.translateLangName_ne;
    case 'sw':
      return l10n.translateLangName_sw;
    case 'af':
      return l10n.translateLangName_af;
    case 'zu':
      return l10n.translateLangName_zu;
    case 'am':
      return l10n.translateLangName_am;
    case 'so':
      return l10n.translateLangName_so;
    case 'ha':
      return l10n.translateLangName_ha;
    case 'yo':
      return l10n.translateLangName_yo;
    case 'ig':
      return l10n.translateLangName_ig;
    case 'hr':
      return l10n.translateLangName_hr;
    case 'sr':
      return l10n.translateLangName_sr;
    case 'sk':
      return l10n.translateLangName_sk;
    case 'sl':
      return l10n.translateLangName_sl;
    case 'lt':
      return l10n.translateLangName_lt;
    case 'lv':
      return l10n.translateLangName_lv;
    case 'et':
      return l10n.translateLangName_et;
    case 'is':
      return l10n.translateLangName_is;
    case 'mt':
      return l10n.translateLangName_mt;
    case 'ga':
      return l10n.translateLangName_ga;
    case 'cy':
      return l10n.translateLangName_cy;
    case 'sq':
      return l10n.translateLangName_sq;
    case 'kk':
      return l10n.translateLangName_kk;
    case 'uz':
      return l10n.translateLangName_uz;
    case 'mn':
      return l10n.translateLangName_mn;
    case 'tl':
      return l10n.translateLangName_tl;
    case 'ht':
      return l10n.translateLangName_ht;
    case 'eo':
      return l10n.translateLangName_eo;
    case 'la':
      return l10n.translateLangName_la;
    case 'ku':
      return l10n.translateLangName_ku;
    case 'ps':
      return l10n.translateLangName_ps;
    case 'fa-AF':
      return l10n.translateLangName_faAf;
    case 'bs':
      return l10n.translateLangName_bs;
    case 'xh':
      return l10n.translateLangName_xh;
    case 'sn':
      return l10n.translateLangName_sn;
    case 'mi':
      return l10n.translateLangName_mi;
    case 'sm':
      return l10n.translateLangName_sm;
    case 'haw':
      return l10n.translateLangName_haw;
    case 'lb':
      return l10n.translateLangName_lb;
    case 'kn':
      return l10n.translateLangName_kn;
    case 'mk':
      return l10n.translateLangName_mk;
    case 'be':
      return l10n.translateLangName_be;
    case 'az':
      return l10n.translateLangName_az;
    case 'hy':
      return l10n.translateLangName_hy;
    case 'ka':
      return l10n.translateLangName_ka;
    case 'lo':
      return l10n.translateLangName_lo;
    case 'km':
      return l10n.translateLangName_km;
    case 'my':
      return l10n.translateLangName_my;
    case 'rw':
      return l10n.translateLangName_rw;
    case 'st':
      return l10n.translateLangName_st;
    case 'mg':
      return l10n.translateLangName_mg;
    case 'ca':
      return l10n.translateLangName_ca;
    default:
      return code;
  }
}
