class LanguageModel {
  final String name;
  final String code;

  const LanguageModel({required this.name, required this.code});
}

const List<LanguageModel> languages = [
  LanguageModel(name: "English", code: "en"),
  LanguageModel(name: "Urdu", code: "ur"),
  LanguageModel(name: "Hindi", code: "hi"),
  LanguageModel(name: "Arabic", code: "ar"),
  LanguageModel(name: "Spanish", code: "es"),
  LanguageModel(name: "French", code: "fr"),
  LanguageModel(name: "German", code: "de"),
  LanguageModel(name: "Portuguese", code: "pt"),
  LanguageModel(name: "Russian", code: "ru"),
  LanguageModel(name: "Chinese (Simplified)", code: "zh"),
  LanguageModel(name: "Chinese (Traditional)", code: "zh-TW"),
  LanguageModel(name: "Japanese", code: "ja"),
  LanguageModel(name: "Korean", code: "ko"),
  LanguageModel(name: "Italian", code: "it"),
  LanguageModel(name: "Turkish", code: "tr"),
  LanguageModel(name: "Dutch", code: "nl"),
  LanguageModel(name: "Swedish", code: "sv"),
  LanguageModel(name: "Norwegian", code: "no"),
  LanguageModel(name: "Danish", code: "da"),
  LanguageModel(name: "Finnish", code: "fi"),
  LanguageModel(name: "Greek", code: "el"),
  LanguageModel(name: "Polish", code: "pl"),
  LanguageModel(name: "Czech", code: "cs"),
  LanguageModel(name: "Hungarian", code: "hu"),
  LanguageModel(name: "Romanian", code: "ro"),
  LanguageModel(name: "Bulgarian", code: "bg"),
  LanguageModel(name: "Ukrainian", code: "uk"),
  LanguageModel(name: "Persian", code: "fa"),
  LanguageModel(name: "Hebrew", code: "he"),
  LanguageModel(name: "Thai", code: "th"),
  LanguageModel(name: "Vietnamese", code: "vi"),
  LanguageModel(name: "Indonesian", code: "id"),
  LanguageModel(name: "Malay", code: "ms"),
  LanguageModel(name: "Bengali", code: "bn"),
  LanguageModel(name: "Tamil", code: "ta"),
  LanguageModel(name: "Telugu", code: "te"),
  LanguageModel(name: "Marathi", code: "mr"),
  LanguageModel(name: "Gujarati", code: "gu"),
  LanguageModel(name: "Punjabi", code: "pa"),
  LanguageModel(name: "Malayalam", code: "ml"),
  LanguageModel(name: "Sinhala", code: "si"),
  LanguageModel(name: "Nepali", code: "ne"),
  LanguageModel(name: "Swahili", code: "sw"),
  LanguageModel(name: "Afrikaans", code: "af"),
  LanguageModel(name: "Zulu", code: "zu"),
  LanguageModel(name: "Amharic", code: "am"),
  LanguageModel(name: "Somali", code: "so"),
  LanguageModel(name: "Hausa", code: "ha"),
  LanguageModel(name: "Yoruba", code: "yo"),
  LanguageModel(name: "Igbo", code: "ig"),
  LanguageModel(name: "Croatian", code: "hr"),
  LanguageModel(name: "Serbian", code: "sr"),
  LanguageModel(name: "Slovak", code: "sk"),
  LanguageModel(name: "Slovenian", code: "sl"),
  LanguageModel(name: "Lithuanian", code: "lt"),
  LanguageModel(name: "Latvian", code: "lv"),
  LanguageModel(name: "Estonian", code: "et"),
  LanguageModel(name: "Icelandic", code: "is"),
  LanguageModel(name: "Maltese", code: "mt"),
  LanguageModel(name: "Irish", code: "ga"),
  LanguageModel(name: "Welsh", code: "cy"),
  LanguageModel(name: "Albanian", code: "sq"),
  LanguageModel(name: "Kazakh", code: "kk"),
  LanguageModel(name: "Uzbek", code: "uz"),
  LanguageModel(name: "Mongolian", code: "mn"),
  LanguageModel(name: "Filipino", code: "tl"),
  LanguageModel(name: "Haitian Creole", code: "ht"),
  LanguageModel(name: "Esperanto", code: "eo"),
  LanguageModel(name: "Latin", code: "la"),
  LanguageModel(name: "Kurdish", code: "ku"),
  LanguageModel(name: "Pashto", code: "ps"),
  LanguageModel(name: "Dari", code: "fa-AF"),
  LanguageModel(name: "Bosnian", code: "bs"),
  LanguageModel(name: "Xhosa", code: "xh"),
  LanguageModel(name: "Shona", code: "sn"),
  LanguageModel(name: "Maori", code: "mi"),
  LanguageModel(name: "Samoan", code: "sm"),
  LanguageModel(name: "Hawaiian", code: "haw"),
  LanguageModel(name: "Luxembourgish", code: "lb"),
];
